### ISSUE TITLE
Okta - Centos 7 - Platform secure storage failure: zbus error: I/O error: No such file or directory (os error 2) 

### ISSUE THREAD

**Issue by carlosDFonseca** [moritzheiber/crowbar#14]
Running the following in a docker container with Centos 7 

$  crowbar --version                     
crowbar 0.4.5

$ crowbar profiles add test --username email --provider okta --url 'https://myorg.okta.com'
Profile test added successfully!

$ env AWS_PROFILE=test aws s3 ls
Password for email at https://myorg.okta.com: [hidden]
Authentication successful!
Platform secure storage failure: zbus error: I/O error: No such file or directory (os error 2)
Error when retrieving credentials from custom-process:
$

to install crowbar:
1. installed cargo and installed crowbar through cargo
2. ran install -y libdbus-1-dev gnome-keyring libssl-dev dbus-x11 curl

**Comment by moritzheiber** [comment]
You cannot run crowbar in a container that doesn’t have a valid DBus-Session.  I’m guessing that’s the case for your container?

**Comment by carlosDFonseca** [comment]
I was able to start a DBus session by running:

- yum install dbus-x11
- export $(dbus-launch) 
- also had to run yum install gnome-keyring 

Ran into a different issue:

$ env AWS_PROFILE=test aws s3 ls
Password for email at https://myorg.okta.com/: [hidden]
Authentication successful!
Couldn't access platform secure storage: SS error: result not returned from SS API

Error when retrieving credentials from custom-process:
$

both session and dbus are running:

$ dbus-monitor
signal time=1653931034.616058 sender=org.freedesktop.DBus -> destination=:1.11 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired string ":1.11"
signal time=1653931034.616114 sender=org.freedesktop.DBus -> destination=:1.11 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost string ":1.11"

[root@056257147c8b /]# systemctl status dbus
● dbus.service - D-Bus System Message Bus
   Loaded: loaded (/usr/lib/systemd/system/dbus.service; static; vendor preset: disabled)
   Active: active (running) since Mon 2022-05-30 17:10:47 UTC; 7min ago
     Docs: man:dbus-daemon(1)
 Main PID: 52 (dbus-daemon)
   CGroup: /docker/056257147c8b31e2ec820fb6c7cc8b5f2b4eae651a1d3d429f49bd239be6fe52/system.slice/dbus.service
           └─52 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation

May 30 17:10:47 056257147c8b systemd[1]: Started D-Bus System Message Bus.

**Comment by moritzheiber** [comment]
Sorry for delay in answering.

Technically, this isn't a bug. `crowbar` is meant to run with first-level access to facilities that store and retrieve confidential data on any of the three major platforms. These APIs aren't usually available inside containers. You can either emulate them (see [the GitHub Actions setup routine](https://github.com/moritzheiber/crowbar/blob/main/.github/workflows/test-all.yml#L34-L48=) for the tests for inspiration) or mount the right paths and/or adjust access rights to the proper channels from within the container in order to get `crowbar` running properly.

I'll consider providing a container image in the future, but it's not a priority right now. PRs are welcome, obviously.

What I will not implement is a mode in which `crowbar` doesn't store its credentials securely (i.e. fall back to a text file when the secret store isn't available). `crowbar` was created with the explicit intend to not expose credentials to the file system and I'd like to stick to that philosophy.

I hope that provides enough insights for the time being. I'll close this report for the time being. Should you have any other specifics bugs to report please don't hesitate to open another issue. Thanks!
